### ISSUE TITLE
Your program doesn't work.

### ISSUE THREAD

**Issue by GuYunxian** [lopuhin/kaggle-dstl#2]
made a mistake when I ran the train.py.

RuntimeError: the given numpy array has zero-sized dimensions. Zero-sized dimensions are not supported in PyTorch

**Comment by lopuhin** [comment]
@GuYunxian yes, it's more of a code dump than a supported project, although it used to work. Could you share the full traceback?

**Comment by GuYunxian** [comment]
Traceback (most recent call last):
  File "./train.py", line 704, in <module>
    main()
  File "./train.py", line 699, in main
    model_path=args.model_path
  File "./train.py", line 172, in train
    no_mp=no_mp)
  File "./train.py", line 308, in train_on_images
    self._train_on_feeds(gen_batch, n_batches, no_mp=no_mp)
  File "./train.py", line 342, in _train_on_feeds
    for i, (x, y, dist_y) in enumerate(map_(gen_batch, range(n_batches))):
  File "/home/huster/fancy/Dstl/kaggle-dstl-master/utils.py", line 282, in imap_fixed_output_buffer
    yield future.result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 405, in result
    return self.__get_result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "./train.py", line 306, in gen_batch
    torch.from_numpy(np.array(dist_outputs)))
RuntimeError: the given numpy array has zero-sized dimensions. Zero-sized dimensions are not supported in PyTorch


I want to run down the results and try it. I wonder if you have an executable program.

**Comment by lopuhin** [comment]
No, I don't have anything more executable. This likely result of missing input data, but I'm not 100% sure - sorry, I didn't put many checks in the code.

**Comment by GuYunxian** [comment]
This error is due to an empty set of parameters.
The parameter dist_output has no input, but you didn't specify how the parameters were set, I am using the default values。

**Comment by HalfLemon** [comment]
Hi, I have the same problem. Do you solve this problem?
